### ISSUE TITLE
timeout, abort console warnings

### ISSUE THREAD

**Issue by frederikhors** [PaulMaly/svelte-viewpoint#2]
I'm getting these warnings in console.

I think we should set them to `null`, am I right?

![image](https://user-images.githubusercontent.com/41120635/74235042-7bab0180-4cce-11ea-8aa0-e3d118b3efbd.png)

**Comment by PaulMaly** [comment]
Hm, I think we just should set default values for them and warnings won't appear anymore. I'll handle it. Thanks!

**Comment by PaulMaly** [comment]
Fixed in 1.2.3
